/* Spanish & Portuguese HTML blocks for timeline + Q&A (English is default in index.html) */
(function () {
  'use strict';

  const TL_ES = `
      <div class="tl-item"><div class="tl-dot navy">0</div><div class="tl-label">Fase 0 — Arranque</div><div class="tl-title">Leer el brief, las clases y repartir el trabajo</div><p class="tl-body">Empezamos leyendo las instrucciones de la tarea y las cinco clases más la conferencia invitada. Acordamos entregables (deck + Jupyter + pitch en vivo), calendario (pitch 10 junio) y roles: diseño de estrategia, back-test en Python, narrativa del deck y preparación de la presentación.</p><div><span class="result-pill pill-blue">PDF de la tarea</span><span class="result-pill pill-gray">Clases 1–5</span><span class="result-pill pill-gray">Roles del equipo</span></div></div>
      <div class="tl-item"><div class="tl-dot blue">1</div><div class="tl-label">Fase 1 — Diseño</div><div class="tl-title">Elegimos long/short transversal en S&amp;P 500</div><p class="tl-body">Combinamos tres señales: momentum 12–1 (Jegadeesh &amp; Titman 1993), baja volatilidad realizada (Ang et al. 2006) y reversión a corto plazo (Lehmann 1990). Construcción con HRP (López de Prado 2016). Dollar-neutral, rebalanceo mensual, 10 bps/lado.</p><div><span class="result-pill pill-gray">Momentum 12–1</span><span class="result-pill pill-gray">Baja vol</span><span class="result-pill pill-gray">Reversión</span><span class="result-pill pill-gray">HRP</span></div></div>
      <div class="tl-item"><div class="tl-dot red">2</div><div class="tl-label">Fase 2 — Resultados</div><div class="tl-title">Alfa negativo: CAGR bruto −0,80%, Sharpe −0,15</div><p class="tl-body">Alfa bruto negativo en 2015–2024. Único punto positivo: ciclo de subida de tipos 2022 (+2,05% neto vs SPY −18,2%).</p><div><span class="result-pill pill-red">CAGR bruto −0,80%</span><span class="result-pill pill-red">Sharpe −0,15</span><span class="result-pill pill-red">Max DD −21,4%</span><span class="result-pill pill-green">2022: +2,05% neto</span></div></div>
      <div class="tl-item"><div class="tl-dot red">3</div><div class="tl-label">Fase 3 — Depuración</div><div class="tl-title">Eliminamos la reversión — empeoró</div><p class="tl-body">Probamos quitar la señal de reversión. Resultado peor: −2,31% CAGR bruto, Sharpe −0,30. La reversión amortiguaba parte de las pérdidas. <strong>Causa raíz: estructural, no de señal.</strong></p><div><span class="result-pill pill-red">Peor: −2,31% bruto</span><span class="result-pill pill-gray">Crowding de factores</span></div></div>
      <div class="tl-item"><div class="tl-dot navy">4</div><div class="tl-label">Fase 4 — Diagnóstico</div><div class="tl-title">Momentum L/S en large-cap USA saturado desde ~2018</div><p class="tl-body">Subrendimiento por crowding de smart beta, crash de momentum Q4 2018 y reversión COVID 2020. La implementación era correcta; el edge ya no está en la misma forma.</p><div><span class="result-pill pill-gray">Crowding post-2018</span><span class="result-pill pill-gray">Crash Q4 2018</span><span class="result-pill pill-gray">Reversión COVID</span></div></div>
      <div class="tl-item"><div class="tl-dot green">5</div><div class="tl-label">Fase 5 — Cambio</div><div class="tl-title">Pasamos a CTA multiactivo trend-following</div><p class="tl-body">Evidencia de décadas (Hurst et al. 2017), sin crowding de un solo factor, alpha en crisis, mecanismo defendible ante el panel. Reescribimos el notebook desde cero.</p><div><span class="result-pill pill-green">CAGR neto +5,86%</span><span class="result-pill pill-green">Sharpe 0,41</span><span class="result-pill pill-blue">GFC +21,6%</span><span class="result-pill pill-blue">2022 +10,2%</span></div></div>
      <div class="tl-item"><div class="tl-dot green">6</div><div class="tl-label">Fase 6 — Implementación CTA</div><div class="tl-title">Apéndice cuantitativo rehecho; bugs corregidos</div><p class="tl-body">Reescritura de <code>quant_appendix.ipynb</code>: 10 ETFs, MA dual (10m+12m), vol-target, IS/OOS 2020. Corregimos Wikipedia 403, pandas 2.x y yfinance. Gráficos exportados a esta web.</p><div><span class="result-pill pill-green">Notebook rehecho</span><span class="result-pill pill-gray">IS/OOS validado</span><span class="result-pill pill-gray">Gráficos exportados</span></div></div>
      <div class="tl-item"><div class="tl-dot green">7</div><div class="tl-label">Fase 7 — Entregables</div><div class="tl-title">Deck, web y prep del pitch — hoy</div><p class="tl-body">Generamos <code>AlphaRidgeCapital_PitchDeck.pptx</code>, esta web con slider allocator y Q&amp;A, narrativa centrada en el <strong>caso allocator</strong> (20% CTA mejora Sharpe y reduce drawdown). Pendiente: ensayo del pitch del 10 de junio.</p><div><span class="result-pill pill-blue">Pitch deck</span><span class="result-pill pill-blue">Esta web</span><span class="result-pill pill-gray">Pitch 10 jun</span></div></div>`;

  const TL_PT = `
      <div class="tl-item"><div class="tl-dot navy">0</div><div class="tl-label">Fase 0 — Arranque</div><div class="tl-title">Ler o brief, as aulas e dividir o trabalho</div><p class="tl-body">Começámos por ler as instruções da tarefa e as cinco aulas mais a palestra convidada. Acordámos entregáveis (deck + Jupyter + pitch ao vivo), calendário (pitch 10 junho) e papéis: estratégia, back-test Python, narrativa do deck e preparação da apresentação.</p><div><span class="result-pill pill-blue">PDF da tarefa</span><span class="result-pill pill-gray">Aulas 1–5</span><span class="result-pill pill-gray">Papéis da equipa</span></div></div>
      <div class="tl-item"><div class="tl-dot blue">1</div><div class="tl-label">Fase 1 — Desenho</div><div class="tl-title">Escolhemos long/short transversal no S&amp;P 500</div><p class="tl-body">Combinámos três sinais: momentum 12–1 (Jegadeesh &amp; Titman 1993), baixa volatilidade realizada (Ang et al. 2006) e reversão de curto prazo (Lehmann 1990). Construção com HRP (López de Prado 2016). Dollar-neutral, rebalanceamento mensal, 10 bps/lado.</p><div><span class="result-pill pill-gray">Momentum 12–1</span><span class="result-pill pill-gray">Baixa vol</span><span class="result-pill pill-gray">Reversão</span><span class="result-pill pill-gray">HRP</span></div></div>
      <div class="tl-item"><div class="tl-dot red">2</div><div class="tl-label">Fase 2 — Resultados</div><div class="tl-title">Alfa negativo: CAGR bruto −0,80%, Sharpe −0,15</div><p class="tl-body">Alfa bruto negativo em 2015–2024. Único ponto positivo: ciclo de subida de taxas 2022 (+2,05% líquido vs SPY −18,2%).</p><div><span class="result-pill pill-red">CAGR bruto −0,80%</span><span class="result-pill pill-red">Sharpe −0,15</span><span class="result-pill pill-red">Max DD −21,4%</span><span class="result-pill pill-green">2022: +2,05% líquido</span></div></div>
      <div class="tl-item"><div class="tl-dot red">3</div><div class="tl-label">Fase 3 — Depuração</div><div class="tl-title">Removemos a reversão — piorou</div><p class="tl-body">Testámos remover o sinal de reversão. Resultado pior: −2,31% CAGR bruto, Sharpe −0,30. A reversão amortecia parte das perdas. <strong>Causa raiz: estrutural, não de sinal.</strong></p><div><span class="result-pill pill-red">Pior: −2,31% bruto</span><span class="result-pill pill-gray">Crowding de fatores</span></div></div>
      <div class="tl-item"><div class="tl-dot navy">4</div><div class="tl-label">Fase 4 — Diagnóstico</div><div class="tl-title">Momentum L/S em large-cap USA saturado desde ~2018</div><p class="tl-body">Subdesempenho por crowding de smart beta, crash de momentum Q4 2018 e reversão COVID 2020. A implementação estava correta; o edge já não existe na mesma forma.</p><div><span class="result-pill pill-gray">Crowding pós-2018</span><span class="result-pill pill-gray">Crash Q4 2018</span><span class="result-pill pill-gray">Reversão COVID</span></div></div>
      <div class="tl-item"><div class="tl-dot green">5</div><div class="tl-label">Fase 5 — Mudança</div><div class="tl-title">Mudámos para CTA multiativo trend-following</div><p class="tl-body">Evidência de décadas (Hurst et al. 2017), sem crowding de um único fator, alpha em crises, mecanismo defensável perante o painel. Reescrevemos o notebook do zero.</p><div><span class="result-pill pill-green">CAGR líquido +5,86%</span><span class="result-pill pill-green">Sharpe 0,41</span><span class="result-pill pill-blue">GFC +21,6%</span><span class="result-pill pill-blue">2022 +10,2%</span></div></div>
      <div class="tl-item"><div class="tl-dot green">6</div><div class="tl-label">Fase 6 — Implementação CTA</div><div class="tl-title">Apêndice quantitativo refeito; bugs corrigidos</div><p class="tl-body">Reescrita de <code>quant_appendix.ipynb</code>: 10 ETFs, MA dupla (10m+12m), vol-target, IS/OOS 2020. Corrigimos Wikipedia 403, pandas 2.x e yfinance. Gráficos exportados para este site.</p><div><span class="result-pill pill-green">Notebook refeito</span><span class="result-pill pill-gray">IS/OOS validado</span><span class="result-pill pill-gray">Gráficos exportados</span></div></div>
      <div class="tl-item"><div class="tl-dot green">7</div><div class="tl-label">Fase 7 — Entregáveis</div><div class="tl-title">Deck, site e prep do pitch — hoje</div><p class="tl-body">Gerámos <code>AlphaRidgeCapital_PitchDeck.pptx</code>, este site com slider allocator e Q&amp;A, narrativa centrada no <strong>caso allocator</strong> (20% CTA melhora Sharpe e reduz drawdown). Pendente: ensaio do pitch de 10 de junho.</p><div><span class="result-pill pill-blue">Pitch deck</span><span class="result-pill pill-blue">Este site</span><span class="result-pill pill-gray">Pitch 10 jun</span></div></div>`;

  function qaBlock(q, a, open) {
    return `<div class="qa-item${open ? ' open' : ''}"><div class="qa-q" onclick="toggleQA(this)">${q}<span class="chevron">&#9660;</span></div><div class="qa-a">${a}</div></div>`;
  }

  const QA_ES = [
    qaBlock('«Su Sharpe es 0,41. El 60/40 tiene 0,84. ¿Por qué debería invertir?»',
      'La comparación es engañosa: no competimos con 60/40, lo <strong>complementamos</strong>. Correlación −0,02. Un 20% en nosotros sube el Sharpe de 0,84 a <strong>1,05</strong> y reduce el drawdown de 29,5% a 15,4%. En la GFC 2008: +21,6% nosotros vs −3,9% el 60/40.', true),
    qaBlock('«¿Qué pasa en mercados laterales de baja volatilidad?»',
      'Es la debilidad conocida del trend-following: whipsaw. En 2011 y 2015–2016 sufrimos. Pero ahí el 60/40 suele ir bien: la correlación negativa compensa.', false),
    qaBlock('«¿No es solo data-mining?»',
      'Tres respuestas: Sharpe OOS (0,45) &gt; IS (0,39); la MA dual se eligió por robustez (Hurst 2017), no por barrido; la literatura documenta beneficios en 215 años.', false),
    qaBlock('«¿Por qué no comprar DBMF o KMLM?»',
      'Son buenas alternativas retail. Ofrecemos transparencia total, cuentas gestionadas y sin el fee extra del ETF (0,85–1,0%). Para USD 100M institucional, el acceso directo es más barato.', false),
    qaBlock('«Su max drawdown es 30,6%, igual que el 60/40.»',
      'Los números son similares pero en <strong>periodos distintos</strong>. En 2022 el 60/40 perdió 16,7% y nosotros +10,2%. Combinados 80/20 el drawdown cae a <strong>15,4%</strong>.', false),
    qaBlock('«Solo 10 ETFs. ¿Y futuros y FX?»',
      'Un CTA real opera 50–100+ instrumentos. Usamos ETFs por datos gratuitos, accesibilidad institucional sin infra de futuros, y evidencia académica que generaliza. Más instrumentos probablemente mejorarían el Sharpe.', false)
  ].join('');

  const QA_PT = [
    qaBlock('«O vosso Sharpe é 0,41. O 60/40 tem 0,84. Porque devia investir?»',
      'A comparação engana: não competimos com 60/40, <strong>complementamos</strong>. Correlação −0,02. 20% connosco sobe o Sharpe de 0,84 para <strong>1,05</strong> e reduz o drawdown de 29,5% para 15,4%. Na GFC 2008: +21,6% nós vs −3,9% o 60/40.', true),
    qaBlock('«O que acontece em mercados laterais de baixa volatilidade?»',
      'É a fraqueza conhecida do trend-following: whipsaw. Em 2011 e 2015–2016 sofremos. Mas aí o 60/40 costuma ir bem: a correlação negativa compensa.', false),
    qaBlock('«Não é só data-mining?»',
      'Três respostas: Sharpe OOS (0,45) &gt; IS (0,39); a MA dupla foi escolhida por robustez (Hurst 2017), não por varredura; a literatura documenta benefícios em 215 anos.', false),
    qaBlock('«Porque não comprar DBMF ou KMLM?»',
      'São boas alternativas retail. Oferecemos transparência total, contas geridas e sem o fee extra do ETF (0,85–1,0%). Para USD 100M institucional, o acesso direto é mais barato.', false),
    qaBlock('«O vosso max drawdown é 30,6%, igual ao 60/40.»',
      'Os números são parecidos mas em <strong>períodos diferentes</strong>. Em 2022 o 60/40 perdeu 16,7% e nós +10,2%. Combinados 80/20 o drawdown cai para <strong>15,4%</strong>.', false),
    qaBlock('«Só 10 ETFs. E futuros e FX?»',
      'Um CTA real opera 50–100+ instrumentos. Usamos ETFs por dados gratuitos, acessibilidade institucional sem infra de futuros, e evidência académica que generaliza. Mais instrumentos provavelmente melhorariam o Sharpe.', false)
  ].join('');

  const CLASSES_ES = `
    <p style="font-size:0.92rem; color:var(--dgray); margin-bottom:1.5rem;">El curso tiene nueve clases principales más una sesión invitada. Nuestro proyecto es el <strong>Quant Fund Pitch</strong>: estrategia sistemática, back-test honesto, marco de riesgo y pitch institucional.</p>
    <table class="map-table"><thead><tr><th>Clase</th><th>Tema principal</th><th>Dónde aparece en el proyecto</th></tr></thead><tbody>
      <tr><td class="lec">Clase 1</td><td>Retornos, Sharpe, sesgos, back-tests honestos</td><td>Tabla de rendimiento, disclaimers, IS/OOS, metodología</td></tr>
      <tr><td class="lec">Clase 2</td><td>Markowitz, CAPM, APT, benchmarks</td><td>Benchmark 60/40; caso allocator</td></tr>
      <tr><td class="lec">Clase 3</td><td>Riesgo coherente, colas, estrés</td><td>Max drawdown; GFC / COVID / 2022</td></tr>
      <tr><td class="lec">Clase 4</td><td>HRP, risk parity, vol</td><td>Primera estrategia HRP; CTA con vol-targeting</td></tr>
      <tr><td class="lec">Clase 5</td><td>Señales, rebalanceo, back-test</td><td>Señal MA mensual; ejecución t→t+1; costes</td></tr>
      <tr><td class="lec">Invitado</td><td>Agentes IA</td><td>IA declarada; pitch humano</td></tr>
      <tr><td class="lec">Tarea</td><td>Rúbrica quant pitch</td><td>Deck + notebook + pitch en vivo</td></tr>
    </tbody></table>
    <div class="class-grid">
      <div class="class-card"><div class="class-num">Clase 1</div><h3>Fundamentos de gestión de activos</h3><p class="class-topic">Mercados, retornos, eficiencia — investigación honesta</p><ul><li>Reportamos <strong>CAGR, volatilidad, Sharpe, max drawdown, Calmar, hit rate</strong>.</li><li>Abordamos <strong>look-ahead, survivorship y Sharpe inflado</strong> en <a href="#methodology">Metodología</a>.</li><li>Todo sale de <code>quant_appendix.ipynb</code>, etiquetado como simulado.</li></ul><p class="project-link">→ Resultados y Metodología</p></div>
      <div class="class-card"><div class="class-num">Clase 2</div><h3>Teoría clásica de carteras</h3><p class="class-topic">Markowitz, CAPM, APT</p><ul><li><strong>Benchmark 60/40</strong> (SPY + IEF) como referencia institucional.</li><li>Primera estrategia: <strong>factores transversales</strong> (momentum, baja vol).</li><li>No competimos con 60/40 en aislamiento; vendemos <strong>diversificación</strong> (correlación ≈ 0).</li></ul><p class="project-link">→ Caso allocator y Fase 1 del Journey</p></div>
      <div class="class-card"><div class="class-num">Clase 3</div><h3>Medidas de riesgo no gaussianas</h3><p class="class-topic">VaR/CVaR, colas, estrés</p><ul><li><strong>Max drawdown</strong> y retornos en crisis como métricas de cola.</li><li>Tres <strong>escenarios de estrés</strong> (GFC, COVID, 2022).</li><li>Drawdowns del CTA y 60/40 <strong>no coinciden en el tiempo</strong>.</li></ul><p class="project-link">→ Escenarios de estrés</p></div>
      <div class="class-card"><div class="class-num">Clase 4</div><h3>Construcción avanzada de carteras</h3><p class="class-topic">HRP, risk parity</p><ul><li>Primera estrategia con <strong>HRP</strong> (López de Prado).</li><li>CTA final con <strong>vol-targeting</strong> — igual contribución al riesgo.</li><li>MA dual por <strong>robustez</strong>, no optimización.</li></ul><p class="project-link">→ Estrategia y Journey Fases 1 y 5–6</p></div>
      <div class="class-card"><div class="class-num">Clase 5</div><h3>Elección dinámica y back-testing</h3><p class="class-topic">Señales, ejecución, gobernanza</p><ul><li><strong>Momentum temporal</strong> (precio vs MA), rebalanceo mensual.</li><li>Señal al cierre de <em>t</em>, posiciones al open de <em>t+1</em>.</li><li><strong>Turnover, costes 5 bps/lado y capacidad</strong> documentados.</li></ul><p class="project-link">→ Apéndice cuantitativo</p></div>
      <div class="class-card guest"><div class="class-num" style="color:var(--amber);">Clase invitada</div><h3>Agentes IA en finanzas</h3><p class="class-topic">David Pacheco Aznar — uso responsable</p><ul><li>IA permitida con <strong>declaración</strong> — investigación, código, web.</li><li>Sin track record en vivo generado por IA.</li><li>Pitch y Q&A <strong>humanos</strong>.</li></ul><p class="project-link">→ Proceso del equipo</p></div>
    </div>
    <div class="info-box" style="margin-top:0.5rem;"><h3>Cómo se mapean los tres entregables</h3><ul>
      <li><span class="bullet"></span><div><span class="tag">Deck</span> Edge + allocator + estrés — Clases 1–3</div></li>
      <li><span class="bullet"></span><div><span class="tag">Notebook</span> Back-test IS/OOS — Clases 1, 4, 5</div></li>
      <li><span class="bullet"></span><div><span class="tag">Pitch</span> Defensa Q&A — sección Q&A Prep</div></li>
    </ul></div>
    <p class="disclaimer">Las clases 6–9 no están en la estrategia final; el crowding de factores (Clase 8) explica el abandono del L/S — ver Journey Fase 4.</p>`;

  const CLASSES_PT = `
    <p style="font-size:0.92rem; color:var(--dgray); margin-bottom:1.5rem;">O curso tem nove aulas principais mais uma sessão convidada. O nosso projeto é o <strong>Quant Fund Pitch</strong>: estratégia sistemática, back-test honesto, quadro de risco e pitch institucional.</p>
    <table class="map-table"><thead><tr><th>Aula</th><th>Tema principal</th><th>Onde aparece no projeto</th></tr></thead><tbody>
      <tr><td class="lec">Aula 1</td><td>Retornos, Sharpe, vieses, back-tests honestos</td><td>Tabela de desempenho, disclaimers, IS/OOS, metodologia</td></tr>
      <tr><td class="lec">Aula 2</td><td>Markowitz, CAPM, APT, benchmarks</td><td>Benchmark 60/40; caso allocator</td></tr>
      <tr><td class="lec">Aula 3</td><td>Risco coerente, caudas, stress</td><td>Max drawdown; GFC / COVID / 2022</td></tr>
      <tr><td class="lec">Aula 4</td><td>HRP, risk parity, vol</td><td>Primeira estratégia HRP; CTA com vol-targeting</td></tr>
      <tr><td class="lec">Aula 5</td><td>Sinais, rebalanceamento, back-test</td><td>Sinal MA mensal; execução t→t+1; custos</td></tr>
      <tr><td class="lec">Convidado</td><td>Agentes IA</td><td>IA declarada; pitch humano</td></tr>
      <tr><td class="lec">Tarefa</td><td>Rúbrica quant pitch</td><td>Deck + notebook + pitch ao vivo</td></tr>
    </tbody></table>
    <div class="class-grid">
      <div class="class-card"><div class="class-num">Aula 1</div><h3>Fundamentos de gestão de ativos</h3><p class="class-topic">Mercados, retornos, eficiência — investigação honesta</p><ul><li>Reportamos <strong>CAGR, volatilidade, Sharpe, max drawdown, Calmar, hit rate</strong>.</li><li>Abordamos <strong>look-ahead, survivorship e Sharpe inflado</strong> em <a href="#methodology">Metodologia</a>.</li><li>Tudo vem de <code>quant_appendix.ipynb</code>, etiquetado como simulado.</li></ul><p class="project-link">→ Resultados e Metodologia</p></div>
      <div class="class-card"><div class="class-num">Aula 2</div><h3>Teoria clássica de carteiras</h3><p class="class-topic">Markowitz, CAPM, APT</p><ul><li><strong>Benchmark 60/40</strong> (SPY + IEF) como referência institucional.</li><li>Primeira estratégia: <strong>fatores transversais</strong> (momentum, baixa vol).</li><li>Não competimos com 60/40 isoladamente; vendemos <strong>diversificação</strong> (correlação ≈ 0).</li></ul><p class="project-link">→ Caso allocator e Fase 1 do Journey</p></div>
      <div class="class-card"><div class="class-num">Aula 3</div><h3>Medidas de risco não gaussianas</h3><p class="class-topic">VaR/CVaR, caudas, stress</p><ul><li><strong>Max drawdown</strong> e retornos em crises como métricas de cauda.</li><li>Três <strong>cenários de stress</strong> (GFC, COVID, 2022).</li><li>Drawdowns do CTA e 60/40 <strong>não coincidem no tempo</strong>.</li></ul><p class="project-link">→ Cenários de stress</p></div>
      <div class="class-card"><div class="class-num">Aula 4</div><h3>Construção avançada de carteiras</h3><p class="class-topic">HRP, risk parity</p><ul><li>Primeira estratégia com <strong>HRP</strong> (López de Prado).</li><li>CTA final com <strong>vol-targeting</strong> — igual contribuição ao risco.</li><li>MA dupla por <strong>robustez</strong>, não otimização.</li></ul><p class="project-link">→ Estratégia e Journey Fases 1 e 5–6</p></div>
      <div class="class-card"><div class="class-num">Aula 5</div><h3>Escolha dinâmica e back-testing</h3><p class="class-topic">Sinais, execução, governação</p><ul><li><strong>Momentum temporal</strong> (preço vs MA), rebalanceamento mensal.</li><li>Sinal no fecho de <em>t</em>, posições na abertura de <em>t+1</em>.</li><li><strong>Turnover, custos 5 bps/lado e capacidade</strong> documentados.</li></ul><p class="project-link">→ Apêndice quantitativo</p></div>
      <div class="class-card guest"><div class="class-num" style="color:var(--amber);">Aula convidada</div><h3>Agentes IA em finanças</h3><p class="class-topic">David Pacheco Aznar — uso responsável</p><ul><li>IA permitida com <strong>declaração</strong> — investigação, código, web.</li><li>Sem track record em vivo gerado por IA.</li><li>Pitch e Q&A <strong>humanos</strong>.</li></ul><p class="project-link">→ Processo da equipa</p></div>
    </div>
    <div class="info-box" style="margin-top:0.5rem;"><h3>Como se mapeiam os três entregáveis</h3><ul>
      <li><span class="bullet"></span><div><span class="tag">Deck</span> Edge + allocator + stress — Aulas 1–3</div></li>
      <li><span class="bullet"></span><div><span class="tag">Notebook</span> Back-test IS/OOS — Aulas 1, 4, 5</div></li>
      <li><span class="bullet"></span><div><span class="tag">Pitch</span> Defesa Q&A — secção Q&A Prep</div></li>
    </ul></div>
    <p class="disclaimer">As aulas 6–9 não estão na estratégia final; o crowding de fatores (Aula 8) explica o abandono do L/S — ver Journey Fase 4.</p>`;

  window.ARC_TIMELINE = { es: TL_ES, pt: TL_PT };
  window.ARC_QA = { es: QA_ES, pt: QA_PT };
  window.ARC_CLASSES = { es: CLASSES_ES, pt: CLASSES_PT };
})();
